version: '3'

services:
  samba:
    tty: true
    network_mode: bridge
    volumes:
      - /backup/Samba/:/Shared:nocopy
    ports:
      - "445:445"
    build:
      context: ./samba
      dockerfile: Dockerfile